---
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash
  args:
    executable: /bin/bash

- name: Install java lts
  shell: "source ~/.sdkman/bin/sdkman-init.sh && sdk install java"
  args:
    executable: /bin/zsh
