---
- name: Install nvm
  homebrew:
    name: nvm
    state: present

- name: Install node lts
  shell: "source {{ ansible_user_dir }}/.nvm/nvm.sh && nvm install --lts"
  args:
    executable: /bin/zsh
