---
- name: Install zsh and plugins
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - "zsh"
    - "zsh-autosuggestions"
    - "zsh-syntax-highlighting"

- name: Remove Oh-My-Zsh folder if exists
  file:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
    state: absent

- name: Install Oh-My-Zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Remove Oh-My-Zsh zshrc generated
  file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: absent

- name: Symlink conf
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link

- name: Set zsh as shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
