---
- name: Install
  homebrew:
    name: koekeishiya/formulae/skhd
    state: present

- name: Symlink conf
  file:
    src: "{{ role_path }}/files/.skhdrc"
    dest: "{{ ansible_user_dir }}/.skhdrc"
    state: link

- name: Start service
  command: brew services start skhd
