---
- name: Install
  homebrew:
    name: tmux
    state: present

- name: Clone TPM
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    version: master

- name: Symlink conf
  file:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link

- name: Install plugins
  shell: sh "{{ ansible_user_dir }}/.tmux/plugins/tpm/bin/install_plugins"
