---
- name: Tapping formulaes
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - "homebrew/cask-fonts"
    - "koekeishiya/formulae"

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - "editorconfig"
    - "fzf"
    - "git-delta"
    - "gnu-tar"
    - "go"
    - "golang-migrate"
    - "helm"
    - "htop"
    - "jq"
    - "kompose"
    - "lazygit"
    - "lazydocker"
    - "librdkafka"
    - "lsd"
    - "maven"
    - "neofetch"
    - "ripgrep"
    - "rust-analyzer"
    - "rustup-init"
    - "starship"

- name: Install apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - "discord"
    - "dotnet-sdk"
    - "docker"
    - "font-hack-nerd-font"
    - "google-chrome"
    - "keycastr"
    - "postman"
