---
- name: Install
  homebrew:
    name: neovim
    state: present

- name: Create folders
  file:
    path: "{{ ansible_user_dir + '/' + item }}"
    mode: 0755
    state: directory
  loop:
    - ".config/nvim"
    - ".config/nvim/lua"
    - ".config/nvim/lua/plugins"
    - ".config/nvim/undodir"
    - ".config/nvim/lsp"
    - ".config/nvim/lsp/omnisharp"
    - ".config/nvim/lsp/jdtls"
    - ".config/nvim/lsp/jdtls/eclipse"
    - ".config/nvim/lsp/jdtls/lombok"
    - ".config/nvim/lsp/jdtls/format"
    - ".config/nvim/dap"
    - ".config/nvim/dap/netcoredbg"

- name: Install go delve
  command: "go install github.com/go-delve/delve/cmd/dlv@latest"

- name: Install gopls
  command: "go install golang.org/x/tools/gopls@latest"

- name: Install goimports
  command: "go install golang.org/x/tools/cmd/goimports@latest"

- name: Install golangci-lint-langserver
  command: "go install github.com/nametake/golangci-lint-langserver@latest"

- name: Install golangci-lint
  command: "go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2"

- name: Install typescript-language-server
  shell: "source {{ ansible_user_dir }}/.zshrc && npm install -g typescript-language-server"
  args:
    executable: /bin/zsh

- name: Install vscode-langservers-extracted
  shell: "source {{ ansible_user_dir }}/.zshrc && npm install -g vscode-langservers-extracted"
  args:
    executable: /bin/zsh

- name: Install @tailwindcss/language-server
  shell: "source {{ ansible_user_dir }}/.zshrc && npm install -g @tailwindcss/language-server"
  args:
    executable: /bin/zsh

- name: Clone go debug adapter
  git:
    repo: "https://github.com/golang/vscode-go"
    dest: "{{ ansible_user_dir }}/.config/nvim/dap/vscode-go"
  register: vscodego_clone
  failed_when:
    - vscodego_clone.failed
    - not 'Local modifications exist' in vscodego_clone.msg

- name: Install go debug adapter deps
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/dap/vscode-go"
    cmd: "source {{ ansible_user_dir }}/.zshrc && npm install"
  args:
    executable: /bin/zsh

- name: Build go debug adapter
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/dap/vscode-go"
    cmd: "source {{ ansible_user_dir }}/.zshrc && npm run bundle"
  args:
    executable: /bin/zsh

- name: Clone nodejs debug adapter
  git:
    repo: "https://github.com/microsoft/vscode-node-debug2.git"
    dest: "{{ ansible_user_dir }}/.config/nvim/dap/vscode-node-debug2"
  register: vscodenodedebug2_clone
  failed_when:
    - vscodenodedebug2_clone.failed
    - not 'Local modifications exist' in vscodenodedebug2_clone.msg

- name: Install nodejs debug adapter deps
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/dap/vscode-node-debug2"
    cmd: "source {{ ansible_user_dir }}/.zshrc && npm install"
  args:
    executable: /bin/zsh

- name: Build nodejs debug adapter
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/dap/vscode-node-debug2"
    cmd: "source {{ ansible_user_dir }}/.zshrc && npm run build"
  args:
    executable: /bin/zsh

- name: Download and unarchive omnihharp-roslyn
  unarchive:
    src: "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.0/omnisharp-osx-x64-net6.0.tar.gz"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/omnisharp"
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Download and unarchive netcoredbg
  unarchive:
    src: "https://github.com/Samsung/netcoredbg/releases/download/2.0.0-915/netcoredbg-osx-amd64.tar.gz"
    dest: "{{ ansible_user_dir }}/.config/nvim/dap/netcoredbg"
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Download and unarchive eclipse.jdt.ls
  unarchive:
    src: "https://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/eclipse"
    remote_src: yes

- name: Clone java-debug
  git:
    repo: "https://github.com/microsoft/java-debug"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/java-debug"
  register: javadebug_clone
  failed_when:
    - javadebug_clone.failed
    - not 'Local modifications exist' in javadebug_clone.msg

- name: Install deps and build java-debug
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/java-debug"
    cmd: "source {{ ansible_user_dir }}/.zshrc && ./mvnw clean install"
  args:
    executable: /bin/zsh

- name: Clone vscode-java-test
  git:
    repo: "https://github.com/microsoft/vscode-java-test"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/vscode-java-test"
  register: vscodejavatest_clone
  failed_when:
    - vscodejavatest_clone.failed
    - not 'Local modifications exist' in vscodejavatest_clone.msg

- name: Install vscode-java-test deps
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/vscode-java-test"
    cmd: "source {{ ansible_user_dir }}/.zshrc && npm install"
  args:
    executable: /bin/zsh

- name: Build vscode-java-test
  shell:
    chdir: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/vscode-java-test"
    cmd: "source {{ ansible_user_dir }}/.zshrc && npm run build-plugin"
  args:
    executable: /bin/zsh

- name: Clone vscode-java-decompiler
  git:
    repo: "https://github.com/dgileadi/vscode-java-decompiler"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/vscode-java-decompiler"
  register: vscodejavadecompiler_clone
  failed_when:
    - vscodejavadecompiler_clone.failed
    - not 'Local modifications exist' in vscodejavadecompiler_clone.msg

- name: Download lombok.jar
  get_url:
    url: "https://projectlombok.org/downloads/lombok.jar"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/lombok/lombok.jar"

- name: Download google-java-format.jar
  get_url:
    url: "https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar"
    dest: "{{ ansible_user_dir }}/.config/nvim/lsp/jdtls/format/google-java-format.jar"

- name: Register conf files
  find:
    paths: "{{ role_path }}/files"
    recurse: yes
  register: nvim_conf

- name: Symlink conf
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_user_dir + '/.config/nvim/' + item.path | regex_replace(role_path + '/files/') }}"
    state: link
  with_items: "{{ nvim_conf.files }}"

- name: Give permissions to java_lsp.sh
  file:
    path: "{{ role_path }}/files/lsp/jdtls/java_lsp.sh"
    mode: 0755
